# This file was generated by GoReleaser. DO NOT EDIT.
cask "bankshot" do
  binary "bankshot"
  binary "bankshotd"

  desc "Automatic SSH port forwarding and browser opening for remote development"
  homepage "https://github.com/phinze/bankshot"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bankshot"

  on_macos do
    on_intel do
      url "https://github.com/phinze/bankshot/releases/download/v0.1.0/bankshot_Darwin_x86_64.tar.gz"
      sha256 "02de358048a326e4835952bb85c0e075804a812f66d164126ad74231ec447bdd"
    end
    on_arm do
      url "https://github.com/phinze/bankshot/releases/download/v0.1.0/bankshot_Darwin_arm64.tar.gz"
      sha256 "7102d811f4daa62b5693db5999774d7a804501a9cdb010d7b9b49633654eb86c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/phinze/bankshot/releases/download/v0.1.0/bankshot_Linux_x86_64.tar.gz"
      sha256 "219ab0e9889a624a541662f8b33575bbf9bbec3c7ca508d3d02479e7c0ae86f3"
    end
    on_arm do
      url "https://github.com/phinze/bankshot/releases/download/v0.1.0/bankshot_Linux_arm64.tar.gz"
      sha256 "cab73b2539f15bace3c554a1163d10dd31e2c137a0ed24677d957fdf95015d74"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bankshot"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bankshotd"]
    end
  end

  # No zap stanza required
end
