# This file was generated by GoReleaser. DO NOT EDIT.
cask "bankshot" do
  binary "bankshot"
  binary "bankshotd"

  desc "Automatic SSH port forwarding and browser opening for remote development"
  homepage "https://github.com/phinze/bankshot"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bankshot"

  on_macos do
    on_intel do
      url "https://github.com/phinze/bankshot/releases/download/v0.1.0/bankshot_darwin_x86_64.tar.gz"
      sha256 "6aa065eba151afb89d2935d619db936deb971f4df65cad6723fbc5079679372a"
    end
    on_arm do
      url "https://github.com/phinze/bankshot/releases/download/v0.1.0/bankshot_darwin_arm64.tar.gz"
      sha256 "4bed77f784dbfa87dab15f33e6a02d67a63f1206811cb99bb8856581fede2479"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/phinze/bankshot/releases/download/v0.1.0/bankshot_linux_x86_64.tar.gz"
      sha256 "a1644595b3553fd7a7c71c79aed5cc6862919bde5b07b0ec452cfe6d1436c46b"
    end
    on_arm do
      url "https://github.com/phinze/bankshot/releases/download/v0.1.0/bankshot_linux_arm64.tar.gz"
      sha256 "7abbfe36513ee76d6e1e66ccce95ac24648da778558bfc088ad292450e494c6a"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bankshot"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bankshotd"]
    end
  end

  # No zap stanza required
end
