# This file was generated by GoReleaser. DO NOT EDIT.
cask "bankshot" do
  binary "bankshot"
  binary "bankshotd"

  desc "Automatic SSH port forwarding and browser opening for remote development"
  homepage "https://github.com/phinze/bankshot"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bankshot"

  on_macos do
    on_intel do
      url "https://github.com/phinze/bankshot/releases/download/v0.2.0/bankshot_darwin_x86_64.tar.gz"
      sha256 "cf13e760593d0c307c0a383cccca50f6bbb2bbe9deb2d345b5bc9063b06c830a"
    end
    on_arm do
      url "https://github.com/phinze/bankshot/releases/download/v0.2.0/bankshot_darwin_arm64.tar.gz"
      sha256 "de0cbd3ffe9a6d1981eb8154d000734d70718e144c0cda4db0cb7e087e88434c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/phinze/bankshot/releases/download/v0.2.0/bankshot_linux_x86_64.tar.gz"
      sha256 "e387ff079c341786342308e588adc00f7b8c2baeb39b186b41d1b5ea2ca97510"
    end
    on_arm do
      url "https://github.com/phinze/bankshot/releases/download/v0.2.0/bankshot_linux_arm64.tar.gz"
      sha256 "e7b5331232f43f518047c67048e9d5c07e8e87e6b62d857c91d49024f05c0452"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bankshot"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bankshotd"]
    end
  end

  # No zap stanza required
end
