# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bankshot < Formula
  desc "Automatic SSH port forwarding and browser opening for remote development"
  homepage "https://github.com/phinze/bankshot"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phinze/bankshot/releases/download/v0.4.0/bankshot_darwin_x86_64.tar.gz"
      sha256 "fc9a3a9d82cccb06f56744d413adfce001bafad9559dfcd002d591cd7b1ced23"

      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phinze/bankshot/releases/download/v0.4.0/bankshot_darwin_arm64.tar.gz"
      sha256 "ea75d5d274cc51f3ea9be5ca9609016fdc6a1a152a1ad445bf3ed06f561bb53b"

      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phinze/bankshot/releases/download/v0.4.0/bankshot_linux_x86_64.tar.gz"
      sha256 "83c45ab07894d1e7211f86034c9493cab7e4d8a5d2e68409ef99b93b406cecb2"
      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phinze/bankshot/releases/download/v0.4.0/bankshot_linux_arm64.tar.gz"
      sha256 "e902ec82270bec7981e6633e72d2cb69f0a60babaad4a8b6b851650569551cb2"
      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
  end

  def caveats
    <<~EOS
      To run bankshotd as a background service:
        brew services start bankshot

      Or run it manually:
        bankshotd
    EOS
  end

  service do
    run [opt_bin/"bankshotd"]
    keep_alive true
    log_path var/"log/bankshotd.log"
    error_log_path var/"log/bankshotd.error.log"
  end

  test do
    system "#{bin}/bankshot", "--version"
  end
end
