# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bankshot < Formula
  desc "Automatic SSH port forwarding and browser opening for remote development"
  homepage "https://github.com/phinze/bankshot"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phinze/bankshot/releases/download/v0.3.0/bankshot_darwin_x86_64.tar.gz"
      sha256 "c05898465fdc6e5918292708c4b9001a5916ed5977479263ec46218c82086e24"

      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phinze/bankshot/releases/download/v0.3.0/bankshot_darwin_arm64.tar.gz"
      sha256 "3d83475a4e57529095b9783081f79bb424516bd5527906bba86a4460f19a283b"

      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/phinze/bankshot/releases/download/v0.3.0/bankshot_linux_x86_64.tar.gz"
      sha256 "e9804d7059ea96333cb5b3fdbcf9edf41d73cd8559e2a66536dd2a705ae38a54"
      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/phinze/bankshot/releases/download/v0.3.0/bankshot_linux_arm64.tar.gz"
      sha256 "b56295560d02ef5846650019d8bc52e990bdda8a65b6861a2a5d7579337734af"
      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
  end

  def caveats
    <<~EOS
      To run bankshotd as a background service:
        brew services start bankshot

      Or run it manually:
        bankshotd
    EOS
  end

  service do
    run [opt_bin/"bankshotd"]
    keep_alive true
    log_path var/"log/bankshotd.log"
    error_log_path var/"log/bankshotd.error.log"
  end

  test do
    system "#{bin}/bankshot", "--version"
  end
end
