# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bankshot < Formula
  desc "Automatic SSH port forwarding and browser opening for remote development"
  homepage "https://github.com/phinze/bankshot"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phinze/bankshot/releases/download/v0.4.0/bankshot_darwin_x86_64.tar.gz"
      sha256 "0ddf46447e623b1d0fd9f6424031bd3d760edf2df8dd71131f5e01f73cee5f94"

      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phinze/bankshot/releases/download/v0.4.0/bankshot_darwin_arm64.tar.gz"
      sha256 "caba5cc1166085165bd93b2444c5a8ee39adee82f55adee6e11c3edb30380236"

      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phinze/bankshot/releases/download/v0.4.0/bankshot_linux_x86_64.tar.gz"
      sha256 "78e6793fa90b7ee1de9b3c85f1401b282f0dc27739cfdb1a9de7ead3b0920072"
      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phinze/bankshot/releases/download/v0.4.0/bankshot_linux_arm64.tar.gz"
      sha256 "8ae2c9119aefddfd3c2a3c662af3c007ca95534c4f8ca50c9743195140c76076"
      def install
        bin.install "bankshot"
        bin.install "bankshotd"
      end
    end
  end

  def caveats
    <<~EOS
      To run bankshotd as a background service:
        brew services start bankshot

      Or run it manually:
        bankshotd
    EOS
  end

  service do
    run [opt_bin/"bankshotd"]
    keep_alive true
    log_path var/"log/bankshotd.log"
    error_log_path var/"log/bankshotd.error.log"
  end

  test do
    system "#{bin}/bankshot", "--version"
  end
end
